---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  encrypted_data_bag_secret_key_path: <%= ENV['HOME'] %>/.chef/encrypted_data_bag_secret
  client_rb:
    environment: 'dev'

platforms:
  - name: ubuntu-14.04
    driver_config:
      customize:
        cpus: 4
        memory: 1536
      network:
        - - private_network
          - ip: '192.168.33.11'

suites:
  - name: default
    run_list:
      - recipe[et_nat::default]
    attributes:
      nat:
        cluster_name: testkitchen
        route_table: rtb-a1b2c3d4
        yaml:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          aws_url: http://192.168.1.191:5000
      ec2:
        instance_id: i-00000003
