---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
provisioner:
  name: chef_zero
  environments_path: '.chef-zero/environments'
  nodes_path: '.chef-zero/nodes'
  data_bags_path: '.chef-zero/data_bags'
# driver:
#   name: ec2
#   require_chef_omnibus: true
#   aws_access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
#   aws_secret_access_key: <%= ENV['AWS_SECRET_KEY'] %>
#   aws_ssh_key_id: aws_dev
#   ssh_key: <%= ENV['HOME'] %>/.ssh/aws_dev.pem
#   subnet_id: subnet-2d2a6c42
#   region: us-east-1
#   availability_zone: us-east-1a
#   security_group_ids: [ "sg-615ebb04" ]

platforms:
- name: ubuntu-12.04
  driver_config:
    customize:
      cpus: 4
      memory: 1536
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box

# platforms:
# - name: ubuntu-12.04
#   driver:
#     username: ubuntu
#     image_id: ami-cf5e2ba6
#     vm:
#       provision:
#         - ['shell', {inline: 'sudo mkdir -p /var/chef && sudo ln -sf /vagrant/.chef-repo/data_bags /var/chef/data_bags'}]

suites:
- name: default
  run_list: ['recipe[et_nat]']
  data_bags_path: ../../server-chef/data_bags
  encrypted_data_bag_secret_key_path: <%= ENV['HOME'] %>/.chef/encrypted_data_bag_secret
  provisioner:
    client_rb:
      environment: 'stage-newvpc'
