---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-12.04
  driver_config:
    customize:
      cpus: 4
      memory: 1536
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box


suites:
- name: default
  run_list: ['recipe[et_nat]']
  data_bags_path: ../../server-chef/data_bags
  encrypted_data_bag_secret_key_path: <%= ENV['HOME'] %>/.chef/encrypted_data_bag_secret
  provisioner:
    client_rb:
      environment: 'stage-newvpc'
