language: ruby
rvm: 2.2
sudo: required
addons:
  apt:
    sources:
      - chef-stable-precise
    packages:
      - chefdk
env:
  - CHEF_BIN=/opt/chefdk/embedded/bin
before_script:
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  # - ${CHEF_BIN}/chef gem install kitchen-ec2
  - "${CHEF_BIN}/berks"
script:
  - "${CHEF_BIN}/chef --version"
  - "${CHEF_BIN}/rubocop --version"
  - "${CHEF_BIN}/rubocop"
  - "${CHEF_BIN}/foodcritic --version"
  - "${CHEF_BIN}/foodcritic ."
  # - KITCHEN_YAML=.kitchen.cloud.yml ${CHEF_BIN}/kitchen test
